"""
Minigame vocabulary dictionary (Cantonese → English).

Mirrors the CANTONESE_TO_ENGLISH map in the frontend
(app/api/generate-image/route.ts) so the image pre-generator can produce
flashcard images for every word used in the learning tab and minigames,
not just the words seeded into PostgreSQL.

Used by pregenerate_images.py to build the full word set
(curated DB words ∪ these minigame words), deduplicated by cache key.
"""

MINIGAME_CANTONESE_TO_ENGLISH: dict[str, str] = {
    # ── Animals ──
    "貓": "cat",
    "狗": "dog",
    "大象": "elephant",
    "獅子": "lion",
    "蝴蝶": "butterfly",
    "魚": "fish",
    "雀仔": "bird",
    "兔仔": "rabbit",
    "猴子": "monkey",
    "龜": "turtle",
    "熊貓": "panda",
    "牛": "cow",
    "鯊魚": "shark",
    "企鵝": "penguin",
    "鹿": "deer",
    "馬": "horse",
    "豬": "pig",
    "羊": "sheep",
    # ── Food ──
    "蘋果": "apple",
    "香蕉": "banana",
    "飯": "rice bowl",
    "麵": "noodles",
    "雞蛋": "egg",
    "奶": "milk",
    "麵包": "bread",
    "水": "water bottle",
    "橙": "orange",
    "紅蘿蔔": "carrot",
    "薄餅": "pizza",
    "雪糕": "ice cream",
    "蛋糕": "cake",
    "西瓜": "watermelon",
    "多士": "toast",
    "曲奇": "cookie",
    "糖": "candy",
    "朱古力": "chocolate",
    "薯條": "french fries",
    "壽司": "sushi",
    # ── Fruits & Vegetables ──
    "提子": "grapes",
    "芒果": "mango",
    "菠蘿": "pineapple",
    "士多啤梨": "strawberry",
    "粟米": "corn",
    "番茄": "tomato",
    "薯仔": "potato",
    "青瓜": "cucumber",
    "蘑菇": "mushroom",
    "洋蔥": "onion",
    "檸檬": "lemon",
    "荔枝": "lychee",
    # ── Toys ──
    "波": "ball",
    "公仔": "doll",
    "熊仔": "teddy bear",
    "積木": "building blocks",
    "機械人": "toy robot",
    "風箏": "kite",
    "氣球": "balloon",
    "鼓": "drum",
    "拼圖": "jigsaw puzzle",
    "跳繩": "jump rope",
    "滑板車": "scooter",
    "陀螺": "spinning top",
    # ── Nature ──
    "樹": "tree",
    "花": "flower",
    "太陽": "sun",
    "雨": "rain",
    "月亮": "moon",
    "星星": "star",
    "雲": "cloud",
    "草": "grass",
    "山": "mountain",
    # ── Stationery ──
    "鉛筆": "pencil",
    "蠟筆": "crayon",
    "剪刀": "scissors",
    "間尺": "ruler",
    "擦膠": "eraser",
    "紙": "paper",
    "膠水": "glue stick",
    "筆": "pen",
    "釘書機": "stapler",
    "膠紙": "tape roll",
    "萬字夾": "paper clip",
    "顏色筆": "marker pen",
    # ── Transportation ──
    "車": "car",
    "巴士": "bus",
    "飛機": "airplane",
    "火車": "train",
    "單車": "bicycle",
    "船": "sailboat",
    "直升機": "helicopter",
    "的士": "taxi",
    "地鐵": "subway train",
    "救護車": "ambulance",
    # ── Places ──
    "屋企": "house",
    "學校": "school",
    "公園": "park",
    "舖頭": "store",
    "沙灘": "beach",
    "圖書館": "library",
    "醫院": "hospital",
    "餐廳": "restaurant",
    "超市": "supermarket",
    "機場": "airport",
    "動物園": "zoo",
    "游泳池": "swimming pool",
    # ── Household Objects ──
    "杯": "cup",
    "匙羹": "spoon",
    "書": "book",
    "凳": "chair",
    "枱": "table",
    "書包": "backpack",
    "遮": "umbrella",
    "鐘": "clock",
    "鎖匙": "key",
    "牙刷": "toothbrush",
    "枕頭": "pillow",
    "被": "blanket",
    "花瓶": "vase",
    "蠟燭": "candle",
    "掃把": "broom",
    # ── Kitchen & Tableware ──
    "碟": "plate",
    "碗": "bowl",
    "叉": "fork",
    "刀": "knife",
    "煲": "pot",
    "鑊": "wok",
    "砧板": "cutting board",
    "微波爐": "microwave",
    "雪櫃": "fridge",
    "焗爐": "oven",
    # ── Bathroom & Hygiene ──
    "毛巾": "towel",
    "梘液": "soap dispenser",
    "洗頭水": "shampoo bottle",
    "廁紙": "toilet paper roll",
    "鏡": "mirror",
    "浴缸": "bathtub",
    "花灑": "shower head",
    "棉花棒": "cotton swab",
    # ── Electronics ──
    "電話": "smartphone",
    "電腦": "laptop",
    "相機": "camera",
    "電視": "television",
    "耳機": "headphones",
    "遙控器": "remote control",
    "手錶": "wristwatch",
    "電燈": "desk lamp",
    # ── Clothing ──
    "衫": "shirt",
    "褲": "pants",
    "鞋": "sneakers",
    "帽": "hat",
    "襪": "socks",
    "裙": "dress",
    "褸": "jacket",
    "眼鏡": "glasses",
    "手套": "gloves",
    "圍巾": "scarf",
    "拖鞋": "slippers",
    "泳衣": "swimsuit",
}
