import psycopg2
from psycopg2 import sql
import sys

def reconcile():
    try:
        conn = psycopg2.connect(dbname="preschool_vocab")
        cur = conn.cursor()
        results = []

        def add_column(table, column, definition):
            cur.execute("SELECT 1 FROM information_schema.columns WHERE table_name = %s AND column_name = %s", (table, column))
            if not cur.fetchone():
                cur.execute(sql.SQL("ALTER TABLE {} ADD COLUMN {} {}").format(
                    sql.Identifier(table),
                    sql.Identifier(column),
                    sql.SQL(definition)
                ))
                results.append(f"Added {table}.{column}")
            else:
                results.append(f"Checked {table}.{column} (already exists)")

        # 1. users: consent columns
        add_column('users', 'consent_given', 'BOOLEAN NOT NULL DEFAULT false')
        add_column('users', 'consent_given_at', 'TIMESTAMPTZ NULL')
        add_column('users', 'consent_camera', 'BOOLEAN NOT NULL DEFAULT true')
        add_column('users', 'consent_microphone', 'BOOLEAN NOT NULL DEFAULT true')
        add_column('users', 'consent_analytics', 'BOOLEAN NOT NULL DEFAULT true')

        # 2. children: community_sharing_enabled
        add_column('children', 'community_sharing_enabled', 'BOOLEAN NOT NULL DEFAULT false')

        # 3. game_sessions
        cur.execute("SELECT 1 FROM information_schema.tables WHERE table_name = 'game_sessions'")
        if not cur.fetchone():
            cur.execute("""
                CREATE TABLE game_sessions (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    child_id VARCHAR NOT NULL REFERENCES children(id) ON DELETE CASCADE,
                    game_id VARCHAR NOT NULL,
                    score INTEGER DEFAULT 0,
                    max_score INTEGER DEFAULT 0,
                    duration_seconds INTEGER DEFAULT 0,
                    stars INTEGER DEFAULT 0,
                    xp_earned INTEGER DEFAULT 0,
                    words_seen JSONB,
                    words_correct JSONB,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                )
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS ix_game_sessions_id ON game_sessions (id)")
            cur.execute("CREATE INDEX IF NOT EXISTS ix_game_sessions_child_id ON game_sessions (child_id)")
            results.append("Created table game_sessions and indexes")
        else:
            results.append("Checked game_sessions (already exists)")

        # 4. stories
        cur.execute("SELECT 1 FROM information_schema.tables WHERE table_name = 'stories'")
        if not cur.fetchone():
            cur.execute("""
                CREATE TABLE stories (
                    id VARCHAR PRIMARY KEY,
                    title VARCHAR NOT NULL,
                    cover_image_url VARCHAR,
                    duration VARCHAR,
                    description TEXT,
                    pages JSONB,
                    target_words JSONB,
                    comprehension_questions JSONB,
                    difficulty VARCHAR DEFAULT 'easy',
                    is_active BOOLEAN DEFAULT true,
                    sort_order INTEGER DEFAULT 0,
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ
                )
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS ix_stories_id ON stories (id)")
            results.append("Created table stories and index")
        else:
            results.append("Checked stories (already exists)")

        # 5. story_progress
        cur.execute("SELECT 1 FROM information_schema.tables WHERE table_name = 'story_progress'")
        if not cur.fetchone():
            cur.execute("""
                CREATE TABLE story_progress (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    child_id VARCHAR NOT NULL REFERENCES children(id),
                    story_id VARCHAR NOT NULL REFERENCES stories(id),
                    completed BOOLEAN DEFAULT false,
                    repeat_count INTEGER DEFAULT 0,
                    last_read TIMESTAMPTZ,
                    pages_completed INTEGER DEFAULT 0,
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ
                )
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS ix_story_progress_id ON story_progress (id)")
            results.append("Created table story_progress and index")
        else:
            results.append("Checked story_progress (already exists)")

        conn.commit()
        print("\n".join(results))
        cur.close()
        conn.close()
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == '__main__':
    reconcile()
