"""
Seed curated bedtime stories with audio generated by the external story program.

Usage:
  python seed_curated_bedtime_stories.py
  python seed_curated_bedtime_stories.py --child-id <child_id> --date 2026-07-09
  python seed_curated_bedtime_stories.py --count 3 --force-refresh-audio
"""

from __future__ import annotations

import argparse
import asyncio
import uuid
from dataclasses import dataclass
from datetime import date, datetime

from sqlalchemy import and_, func, select

from app.db.session import AsyncSessionLocal
# Import related models so SQLAlchemy can resolve string-based relationships.
from app.models.analytics import Achievement, DailyStats, LearningSession  # noqa: F401
from app.models.community import CommunityPost, PostReaction  # noqa: F401
from app.models.content import Game, Mission, Story  # noqa: F401
from app.models.daily_words import DailyWordTracking, GeneratedStory
from app.models.generated_sentences import GeneratedSentence  # noqa: F401
from app.models.parent_analytics import (  # noqa: F401
    DailyLearningStats,
    LearningInsight,
    ParentalControl,
    WeeklyReport,
)
from app.models.user import Child  # noqa: F401
from app.models.vocabulary import Word  # noqa: F401
from app.services.external_story_program_service import (
    ExternalStoryProgramError,
    external_story_program_service,
)
from app.services.story_audio_metadata import resolve_story_audio_duration_seconds


SEED_PROMPT_PREFIX = "seed_curated_bedtime"


@dataclass(frozen=True)
class CuratedBedtimeSeed:
    key: str
    story_category: str
    theme_zh: str
    theme_en: str


CURATED_BEDTIME_STORY_SEEDS: tuple[CuratedBedtimeSeed, ...] = (
    CuratedBedtimeSeed("bedtime-01", "睡前", "睡前", "Bedtime"),
    CuratedBedtimeSeed("bedtime-02", "睡前", "月光", "Moonlight"),
    CuratedBedtimeSeed("bedtime-03", "家庭", "家庭", "Family"),
    CuratedBedtimeSeed("bedtime-04", "友誼", "友誼", "Friendship"),
    CuratedBedtimeSeed("bedtime-05", "動物", "動物", "Animals"),
    CuratedBedtimeSeed("bedtime-06", "大自然", "大自然", "Nature"),
    CuratedBedtimeSeed("bedtime-07", "冒險", "冒險", "Adventure"),
    CuratedBedtimeSeed("bedtime-08", "睡前", "晚安", "Goodnight"),
    CuratedBedtimeSeed("bedtime-09", "家庭", "溫馨", "Cozy Family"),
    CuratedBedtimeSeed("bedtime-10", "友誼", "星空", "Starry Friends"),
)


def _seed_prompt_key(seed_key: str) -> str:
    return f"{SEED_PROMPT_PREFIX}:{seed_key}"


def _default_story_ssml(story_text: str) -> str:
    return f"<speak>{story_text}</speak>"


def _parse_date_or_raise(raw_date: str) -> date:
    try:
        return date.fromisoformat(raw_date)
    except ValueError as error:
        raise ValueError("Date must be in YYYY-MM-DD format.") from error


def _has_ready_aws_audio(story: GeneratedStory | None) -> bool:
    if story is None:
        return False
    if (story.audio_generate_provider or "").strip().lower() != "aws":
        return False
    if not (story.audio_url or "").strip():
        return False
    audio_filename = (story.audio_filename or "").strip().lower()
    if not audio_filename or audio_filename == "curated-story.mp3":
        return False
    return True


async def _find_existing_story(db, seed_key: str) -> GeneratedStory | None:
    result = await db.execute(
        select(GeneratedStory).where(
            GeneratedStory.story_type == "curated",
            GeneratedStory.generation_prompt == _seed_prompt_key(seed_key),
        )
    )
    return result.scalar_one_or_none()


async def _resolve_generation_context(
    db,
    requested_child_id: str | None,
    requested_date: str | None,
) -> tuple[str, str]:
    parsed_date = _parse_date_or_raise(requested_date) if requested_date else None

    if requested_child_id and parsed_date:
        rows_result = await db.execute(
            select(func.count(DailyWordTracking.id)).where(
                and_(
                    DailyWordTracking.child_id == requested_child_id,
                    func.date(DailyWordTracking.date) == parsed_date,
                )
            )
        )
        rows_count = int(rows_result.scalar_one() or 0)
        if rows_count <= 0:
            raise RuntimeError(
                f"No daily_word_tracking rows found for child '{requested_child_id}' on {parsed_date}."
            )
        return requested_child_id, parsed_date.isoformat()

    if requested_child_id and not parsed_date:
        latest_result = await db.execute(
            select(DailyWordTracking.date)
            .where(DailyWordTracking.child_id == requested_child_id)
            .order_by(DailyWordTracking.date.desc())
            .limit(1)
        )
        latest_date = latest_result.scalar_one_or_none()
        if latest_date is None:
            raise RuntimeError(
                f"No daily_word_tracking rows found for child '{requested_child_id}'."
            )
        return requested_child_id, latest_date.date().isoformat()

    if not requested_child_id and parsed_date:
        row_result = await db.execute(
            select(DailyWordTracking.child_id)
            .where(func.date(DailyWordTracking.date) == parsed_date)
            .order_by(DailyWordTracking.child_id.asc())
            .limit(1)
        )
        child_id = row_result.scalar_one_or_none()
        if child_id is None:
            raise RuntimeError(
                f"No daily_word_tracking rows found on {parsed_date}. "
                "Provide --child-id/--date explicitly."
            )
        return child_id, parsed_date.isoformat()

    latest_row_result = await db.execute(
        select(DailyWordTracking.child_id, DailyWordTracking.date)
        .order_by(DailyWordTracking.date.desc())
        .limit(1)
    )
    latest_row = latest_row_result.first()
    if latest_row is None:
        raise RuntimeError(
            "No daily_word_tracking rows found. "
            "Generate daily word tracking first, then run this seed script."
        )

    return latest_row.child_id, latest_row.date.date().isoformat()


def _build_seed_titles(seed: CuratedBedtimeSeed, index: int) -> tuple[str, str]:
    return (
        f"晚安精選故事 {index:02d}｜{seed.theme_zh}",
        f"Curated Bedtime Story {index:02d} | {seed.theme_en}",
    )


async def seed_curated_bedtime_stories(
    force_refresh_audio: bool = False,
    child_id: str | None = None,
    gen_date: str | None = None,
    count: int = 10,
) -> None:
    availability_error = external_story_program_service.availability_error()
    if availability_error:
        raise RuntimeError(
            "Cannot seed curated bedtime stories because the external story generation "
            f"program is unavailable: {availability_error}"
        )

    if count <= 0:
        raise ValueError("--count must be at least 1")

    seeds_to_process = CURATED_BEDTIME_STORY_SEEDS[:count]

    async with AsyncSessionLocal() as db:
        source_child_id, source_date = await _resolve_generation_context(db, child_id, gen_date)
        print(
            "Using external story generation context:",
            {"child_id": source_child_id, "date": source_date, "seed_count": len(seeds_to_process)},
        )

        created_count = 0
        updated_count = 0
        audio_generated_count = 0
        audio_reused_count = 0

        for index, seed in enumerate(seeds_to_process, start=1):
            existing_story = await _find_existing_story(db, seed.key)
            story = existing_story
            title, title_english = _build_seed_titles(seed, index)

            should_generate = force_refresh_audio or not _has_ready_aws_audio(existing_story)

            if should_generate:
                print(
                    f"🎙️  Generating story {index}/{len(seeds_to_process)} "
                    f"for category={seed.story_category}"
                )
                try:
                    generated_result = await asyncio.to_thread(
                        external_story_program_service.invoke,
                        source_child_id,
                        source_date,
                        seed.story_category,
                    )
                except ExternalStoryProgramError as error:
                    raise RuntimeError(
                        f"Failed to generate seeded bedtime story {index} ({seed.key}): {error}"
                    ) from error

                if (generated_result.tts_provider or "").strip().lower() != "aws":
                    raise RuntimeError(
                        f"Expected AWS Polly audio for seed {seed.key}, "
                        f"but got provider '{generated_result.tts_provider}'."
                    )

                if story is None:
                    story = GeneratedStory(id=str(uuid.uuid4()))
                    db.add(story)
                    created_count += 1
                else:
                    updated_count += 1

                generated_at = generated_result.generated_at
                if generated_at.tzinfo is not None:
                    generated_at = generated_at.replace(tzinfo=None)

                story.child_id = None
                story.story_type = "curated"
                story.title = title
                story.title_english = title_english
                story.theme = "bedtime"
                story.generated_at = generated_at
                story.generated_by = "seed_curated_bedtime_stories"
                story.content_cantonese = generated_result.story_text
                story.story_text = generated_result.story_text
                story.story_text_ssml = (
                    generated_result.story_text_ssml
                    or _default_story_ssml(generated_result.story_text)
                )
                story.vocab_used = generated_result.vocab_used
                story.story_generate_provdier = "external_story_program"
                story.story_generate_model = generated_result.llm_model
                story.featured_words = []
                story.word_usage = None
                story.audio_url = generated_result.audio_url
                story.audio_filename = generated_result.audio_filename
                story.page_audio_segments = generated_result.page_audio_segments or None
                story.audio_generate_provider = generated_result.tts_provider
                story.audio_generate_voice_name = generated_result.voice_name
                story.reading_time_minutes = 5
                story.word_count = len(generated_result.story_text)
                story.difficulty_level = "easy"
                story.cultural_references = []
                story.is_active = True
                story.parent_approved = True
                story.sort_order = index
                story.ai_model = generated_result.llm_model
                story.generation_prompt = _seed_prompt_key(seed.key)
                story.audio_duration_seconds = resolve_story_audio_duration_seconds(story)
                audio_generated_count += 1
            else:
                if story is None:
                    raise RuntimeError(
                        f"Unexpected state for seed {seed.key}: story missing while audio is reused."
                    )
                story.title = title
                story.title_english = title_english
                story.theme = "bedtime"
                story.generated_by = story.generated_by or "seed_curated_bedtime_stories"
                story.is_active = True
                story.parent_approved = True
                story.sort_order = index
                story.generation_prompt = _seed_prompt_key(seed.key)
                story.audio_duration_seconds = resolve_story_audio_duration_seconds(story)
                updated_count += 1
                audio_reused_count += 1

        await db.commit()

        print(
            "✅ Curated bedtime story seeding complete:",
            {
                "seed_count": len(seeds_to_process),
                "created": created_count,
                "updated": updated_count,
                "audio_generated": audio_generated_count,
                "audio_reused": audio_reused_count,
                "source_child_id": source_child_id,
                "source_date": source_date,
            },
        )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Seed curated bedtime stories and generate audio through the external "
            "story-generation program."
        )
    )
    parser.add_argument(
        "--force-refresh-audio",
        action="store_true",
        help="Regenerate audio for all seeded stories even if existing AWS Polly audio is present.",
    )
    parser.add_argument(
        "--child-id",
        type=str,
        default=None,
        help="Optional child_id used by the external program for vocab lookup.",
    )
    parser.add_argument(
        "--date",
        type=str,
        default=None,
        help="Optional generation date (YYYY-MM-DD) used by the external program for vocab lookup.",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=10,
        help="Number of seed stories to process (max 10).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    asyncio.run(
        seed_curated_bedtime_stories(
            force_refresh_audio=args.force_refresh_audio,
            child_id=args.child_id,
            gen_date=args.date,
            count=min(len(CURATED_BEDTIME_STORY_SEEDS), args.count),
        )
    )
