"""add_parent_analytics_tables

Revision ID: 74e12a1dca87
Revises: 1f6c13cb81cd
Create Date: 2026-02-01 01:47:12.893479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e12a1dca87'
down_revision = '1f6c13cb81cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_learning_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('words_learned', sa.Integer(), nullable=True),
    sa.Column('words_reviewed', sa.Integer(), nullable=True),
    sa.Column('new_words_mastered', sa.Integer(), nullable=True),
    sa.Column('total_learning_time', sa.Integer(), nullable=True),
    sa.Column('active_learning_time', sa.Integer(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('categories_studied', sa.JSON(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_completed', sa.Integer(), nullable=True),
    sa.Column('stories_read', sa.Integer(), nullable=True),
    sa.Column('bedtime_stories_generated', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_learning_stats_child_id'), 'daily_learning_stats', ['child_id'], unique=False)
    op.create_index(op.f('ix_daily_learning_stats_date'), 'daily_learning_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_learning_stats_id'), 'daily_learning_stats', ['id'], unique=False)
    op.create_table('learning_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.String(), nullable=True),
    sa.Column('valid_until', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_insights_child_id'), 'learning_insights', ['child_id'], unique=False)
    op.create_index(op.f('ix_learning_insights_id'), 'learning_insights', ['id'], unique=False)
    op.create_table('parental_controls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('enabled_categories', sa.JSON(), nullable=True),
    sa.Column('disabled_categories', sa.JSON(), nullable=True),
    sa.Column('max_difficulty', sa.String(), nullable=True),
    sa.Column('min_difficulty', sa.String(), nullable=True),
    sa.Column('daily_screen_time_limit', sa.Integer(), nullable=True),
    sa.Column('screen_time_warning_threshold', sa.Integer(), nullable=True),
    sa.Column('tts_voice', sa.String(), nullable=True),
    sa.Column('tts_speech_rate', sa.Float(), nullable=True),
    sa.Column('enable_bilingual_mode', sa.Boolean(), nullable=True),
    sa.Column('show_jyutping', sa.Boolean(), nullable=True),
    sa.Column('game_difficulty_multiplier', sa.Float(), nullable=True),
    sa.Column('enable_time_limits', sa.Boolean(), nullable=True),
    sa.Column('safe_mode_enabled', sa.Boolean(), nullable=True),
    sa.Column('require_parent_unlock', sa.Boolean(), nullable=True),
    sa.Column('daily_reminder_enabled', sa.Boolean(), nullable=True),
    sa.Column('daily_reminder_time', sa.String(), nullable=True),
    sa.Column('bedtime_story_reminder', sa.Boolean(), nullable=True),
    sa.Column('weekly_report_enabled', sa.Boolean(), nullable=True),
    sa.Column('achievement_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parental_controls_child_id'), 'parental_controls', ['child_id'], unique=True)
    op.create_index(op.f('ix_parental_controls_id'), 'parental_controls', ['id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('total_words_learned', sa.Integer(), nullable=True),
    sa.Column('total_learning_time', sa.Integer(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('days_active', sa.Integer(), nullable=True),
    sa.Column('milestones_reached', sa.JSON(), nullable=True),
    sa.Column('new_badges_earned', sa.JSON(), nullable=True),
    sa.Column('top_categories', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('areas_to_improve', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('growth_percentage', sa.Float(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reports_child_id'), 'weekly_reports', ['child_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_id'), 'weekly_reports', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_start_date'), 'weekly_reports', ['week_start_date'], unique=False)
    op.create_index(op.f('ix_daily_word_tracking_id'), 'daily_word_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_generated_stories_id'), 'generated_stories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_stories_id'), table_name='generated_stories')
    op.drop_index(op.f('ix_daily_word_tracking_id'), table_name='daily_word_tracking')
    op.drop_index(op.f('ix_weekly_reports_week_start_date'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_child_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_parental_controls_id'), table_name='parental_controls')
    op.drop_index(op.f('ix_parental_controls_child_id'), table_name='parental_controls')
    op.drop_table('parental_controls')
    op.drop_index(op.f('ix_learning_insights_id'), table_name='learning_insights')
    op.drop_index(op.f('ix_learning_insights_child_id'), table_name='learning_insights')
    op.drop_table('learning_insights')
    op.drop_index(op.f('ix_daily_learning_stats_id'), table_name='daily_learning_stats')
    op.drop_index(op.f('ix_daily_learning_stats_date'), table_name='daily_learning_stats')
    op.drop_index(op.f('ix_daily_learning_stats_child_id'), table_name='daily_learning_stats')
    op.drop_table('daily_learning_stats')
    # ### end Alembic commands ###
