"""add_generated_sentences_table

Revision ID: 7d1dc1c04fdd
Revises: 9c7f3d1a2e1b
Create Date: 2026-02-06 12:39:12.280457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1dc1c04fdd'
down_revision = '9c7f3d1a2e1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_sentences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_id', sa.String(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('sentence_english', sa.Text(), nullable=False),
    sa.Column('jyutping', sa.Text(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_sentences_id'), 'generated_sentences', ['id'], unique=False)
    op.create_index(op.f('ix_generated_sentences_word_id'), 'generated_sentences', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_sentences_word_id'), table_name='generated_sentences')
    op.drop_index(op.f('ix_generated_sentences_id'), table_name='generated_sentences')
    op.drop_table('generated_sentences')
    # ### end Alembic commands ###
